### ISSUE TITLE
Process is remain after application is closed

### ISSUE THREAD

**Issue by NorikatsuTanaka** [Gainedge/BetterExplorer#126]
Process is remain in background process (not always) even after application is closed.
I don't know if it's OK?

![process view](https://user-images.githubusercontent.com/48576320/54529604-ac51c080-49c3-11e9-8adc-2065dda07394.jpg)

**Comment by NorikatsuTanaka** [comment]
More information.
While application is on running even it was closed, error window "can not find path or internet address" is popped up periodically.

**Comment by DimitarCC** [comment]
Hello,

I know about this stuck problem.
You using quite old build of Better Explorer (although its the latest compiled available).
There is many modifications after this including many speed fixes and new full Dark mode to support recent versions of Windows 10.
In that versions this issue is fixed :)
However that builds are still private and required .NET Framework 4.7.2 to work.
If you like i can provide you with some of internal builds for testing.

Best Regards,
Dimitar Tsenev.

On 19.3.2019 г. 12:09:17, NorikatsuTanaka <notifications@github.com> wrote:

More information.
While application is on running even it was closed, error window "can not find path or internet address" is popped up periodically.

**Comment by NorikatsuTanaka** [comment]
Application says that no latest version available when click "checking update"...
How can I update this?
To tell truth, uninstall is also impossible with this.
When click uninstall at "application and function", installer starts instead of uninstaller.

**Comment by DimitarCC** [comment]
well update is only possible manual. As i said the build is not official and that why is not on live updates.
The uninstall issue should be fixed in the new installers. :)

On 19.3.2019 г. 12:56:19, NorikatsuTanaka <notifications@github.com> wrote:

Application says that no latest version available when click "checking update"...
How can I update this?
To tell truth, uninstall is also impossible with this.
When click uninstall at "application and function", installer starts instead of uninstaller.

**Comment by NorikatsuTanaka** [comment]
Dear Sirs,
Thank you for your advice.
Then let me try latest version to fix all those issues, if possible?
How can I do it for?

**Comment by DimitarCC** [comment]
Well please keep in mind that all that stuff are experimental and you can use it on you own risk.
If you agree with this then i can provide you with an installer that you can execute and install brand new version.

**Comment by NorikatsuTanaka** [comment]
Dear Sirs,

OK, noted.
I can not move without update anyway.
I like to try your proposal
Thank you.

**Comment by DimitarCC** [comment]
[BetterExplorer-v2019.03.20.8.zip](https://github.com/Gainedge/BetterExplorer/files/2988035/BetterExplorer-v2019.03.20.8.zip)

Try this. Unpack it and run BetterExplorer.exe. That is the new installer. I am not sure how it will goes on your side but lets try.
Also don't forget to restart your pc prior to install.

**Comment by NorikatsuTanaka** [comment]
Thank you for inviting latest version.
However, it seems to work still.
- can not find path or internet address, however such files becomes less what I see so far
- remain in background process
- uninstaller does not work properly

Reboot was done before installing latest version.

**Comment by DimitarCC** [comment]
Well let me put some remarks....

-     can not find path or internet address, however such files becomes less what I see so far - this is difficult to overcome since you are using Japanese Windows which maybe is the source of the problem. However i don't have such so is difficult to test.
-     remain in background process - please keep in mind that to exit better explorer completely you should go to File menu -> Exit. Just closing it by "X" button leave it running in system tray.
-     uninstaller does not work properly - the uninstalling process starts the installer and on the second step to it there is "Repair", "Modify" and "Uninstall" options.

**Comment by NorikatsuTanaka** [comment]
Please check my input.

    uninstaller does not work properly - the uninstalling process starts the installer and on the second step to it there is "Repair", "Modify" and "Uninstall" options.

=> those options had not come yet. Always installing process, only.
So I would like to uninstall first, to reset BE system.
Can you provide uninstaller?

**Comment by DimitarCC** [comment]
Well there is not specific uninstaller for this. I didn't come to such a problem yet.
Isn't it work after you install it via that new installer and then try to uninstall it?
Otherwise maybe you will need some external tool so to clear msi cache generated on you PC (keep in mind this could be dangerous)

**Comment by NorikatsuTanaka** [comment]
Can you offer me for cleaning tool?
I really like to retry your application after refreshed.

**Comment by DimitarCC** [comment]
well i am not sure which works good with Windows 10.
maybe you can look at https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
and also you may look at "Windows installer Cleanup utility" (not officially supports Win 10)
