### ISSUE TITLE
No icons displayed

### ISSUE THREAD

**Issue by S-Kosev** [Gainedge/BetterExplorer#130]
![Image 11](https://user-images.githubusercontent.com/61520985/75387138-86c77980-58eb-11ea-9416-b6015fc9743f.png)

**Comment by DimitarCC** [comment]
well what version do you use? Did you built it yourself?

**Comment by S-Kosev** [comment]
2018.06.06.6_RC, he last one, downloaded from the official site, just downloaded, installed, launched and got such a picture. system win7x32

**Comment by S-Kosev** [comment]
2018.06.06.6_RC. he last one, downloaded from the official site, just downloaded, installed, launched and got such a picture. system Win7x32

**Comment by DimitarCC** [comment]
Ahhh i see. Well this is quite old one in matter of the code. It had issues before with x32 systems. Generally it is designed for x64 system. You can try to install the newest alpha version (https://github.com/Gainedge/BetterExplorer/files/2999380/BetterExplorer-v2019.03.22.1.zip) However the newest version of the code no longer supports Windows7 since its way out of support. The only supported version is Windows 10.

**Comment by S-Kosev** [comment]
Сегодня как раз установил v2019.03.22.1 поверх старой (как удалить старую не понял), не не помогло, иконки так и не отображаются:(
"Однако новейшая версия кода больше не поддерживает Windows7 с момента ее появления из поддержки" очень жалко, BetterExplorer почти как раз то что искал.
Спасибо за консультацию
