### ISSUE TITLE
the program does not open

### ISSUE THREAD

**Issue by JPAM937** [Gainedge/BetterExplorer#150]
I'm using Windows 7 SP1 Ultimate x86 and the program opens but closes I've tried to change the compatibility mode but it's still not working any idea what this error is?

**Comment by DimitarCC** [comment]
Hello. Better Explorer is not designed to work on Windows 7 at all since Windows 7 is not supported by Microsoft from long time. The lates public installer is designed to work on Windows 10 and Windows 11 64bit only. And the lates code works on Windows 11 only. So there is no possibility to work on Windows 7 anymore.
